version: '2'
services:
    nav-app:
        image: nav
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://nav-mssql:1433;database=nav
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nav-mssql:
        extends:
            file: mssql.yml
            service: nav-mssql
